TITLE = "Grand Prix"

CAR_SIZE = 16
TEXTURE_SIZE = 8

COLUMNS = 26
ROWS = 16

VIRTUAL_WIDTH = COLUMNS * TEXTURE_SIZE
VIRTUAL_HEIGHT = ROWS * TEXTURE_SIZE

WINDOW_SCALE = 3
WINDOW_WIDTH = VIRTUAL_WIDTH * WINDOW_SCALE
WINDOW_HEIGHT = VIRTUAL_HEIGHT * WINDOW_SCALE

OPTIONS = {
  fullscreen = false,
  vsync = true,
  resizable = true
}

OFFSET_SPEED = 40
OFFSET_SPEED_SET = 20
OFFSET_SPEED_GO = 80

TWEEN_IN = 0.12
TWEEN_OUT = 0.08
