WINDOW_WIDTH = 400
WINDOW_HEIGHT = 400

OPTIONS = {
  fullscreen = false,
  vsync = true,
  resizable = false
}

RECORD = 10000
POINTS = {
  [3] = 20,
  [2] = 50,
  [1] = 100
}
LIVES = 3
LIVES_THRESHOLD_EXTRA = 5000
LIVES_THRESHOLD_TEXT = 6

DIFFICULTY_MIN = 1
DIFFICULTY_MAX = 3
DIFFICULTY_DEFAULT = 2
DIFFICULTY_MULTIPLIER = 2

PLAYER_RADIUS = 8
PLAYER_SPEED = 2
PLAYER_FRICTION = 1
PLAYER_SPEED_LATERAL = 220

PROJECTILE_SPEED = 250
PROJECTILE_RADIUS = 2
PROJECTILE_TIMEOUT = 0.9

ASTEROID_SPEED_MIN = 10
ASTEROID_SPEED_MAX = 50
ASTEROID_DEFAULT_SIZE = 3
ASTEROID_SIZE_MULTIPLIER = 4

ENEMY_ASTEROID_THRESHOLD = 4
ENEMY_ODDS = 500
ENEMY_POINTS = 200
ENEMY_RADIUS = 6
ENEMY_SPEED_X_MIN = 40
ENEMY_SPEED_X_MAX = 100
ENEMY_SPEED_Y_MIN = -30
ENEMY_SPEED_Y_MAX = 30
ENEMY_CHANGE_Y_ODDS = 30

TIMEOUT_VICTORY = 2
TIMEOUT_TELEPORT = 0.75
TIMEOUT_GAMEOVER = 5

INTERVAL_SETUP = 0.15
INTERVAL_SETUP_ITERATIONS = 10
INTERVAL_NOISE = 4
