WINDOW_WIDTH = 400
WINDOW_HEIGHT = 400

OPTIONS = {
  fullscreen = false,
  vsync = true,
  resizable = false
}

RECORD = 35000
POINTS = {
  [3] = 20,
  [2] = 50,
  [1] = 100
}
LIVES = 3
LIVES_THRESHOLD = 10000

DIFFICULTY_MIN = 1
DIFFICULTY_MAX = 3
DIFFICULTY_DEFAULT = 2
DIFFICULTY_MULTIPLIER = 2

PLAYER_RADIUS = 8
PLAYER_SPEED = 2
PLAYER_FRICTION = 1
PLAYER_SPEED_LATERAL = 220

PROJECTILE_SPEED = 250
PROJECTILE_TIMEOUT = 0.9

ASTEROID_SPEED_MIN = 10
ASTEROID_SPEED_MAX = 60
ASTEROID_SIZE_MULTIPLIER = 4

TIMEOUT_VICTORY = 2
TIMEOUT_TELEPORT = 0.75
TIMEOUT_GAMEOVER = 5

INTERVAL_SETUP = 0.15
INTERVAL_SETUP_ITERATIONS = 10
INTERVAL_NOISE = 3
