WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 256
VIRTUAL_HEIGHT = 144

OPTIONS = {
  fullscreen = false,
  vsync = true,
  resizable = true
}

BACKGROUND_WIDTH = VIRTUAL_WIDTH
BACKGROUND_HEIGHT = VIRTUAL_HEIGHT

SCROLL_SPEED = 100
