TITLE = "Bouldy"

MAZE_DIMENSION = 14
CELL_SIZE = 30
MAZE_SIZE = CELL_SIZE * MAZE_DIMENSION

WINDOW_PADDING = 10
WINDOW_MARGIN_TOP = 28

WINDOW_WIDTH = MAZE_SIZE + WINDOW_PADDING * 2
WINDOW_HEIGHT = MAZE_SIZE + WINDOW_MARGIN_TOP + WINDOW_PADDING * 2

COINS = 1
