TITLE = "Missile Command"

WINDOW_WIDTH = 580
WINDOW_HEIGHT = 500

STRUCTURE_SIZE = 46

TARGET_SIZE = 5
TRACKBALL_SIZE = 12
TRACKBALL_UPDATE_SPEED = 100

LINE_RESOLUTION = 5

ANTI_MISSILE_UPDATE_SPEED = 0.0001
MISSILE_UPDATE_SPEED = 0.0009

MISSILES = {
  ["number"] = 10,
  ["delay-max"] = 20,
  ["launch-pad-odds"] = 5
}

EXPLOSION = {
  ["interval"] = 0.2,
  ["radius"] = 18
}
