TITLE = "Missile Command"

WINDOW_WIDTH = 580
WINDOW_HEIGHT = 500

STRUCTURE_SIZE = 46
TARGET_SIZE = 5
TRACKBALL_SIZE = 12

RESOLUTION = 5
ANTI_MISSILE_TIME = 1.5

MISSILE_TIME = 25
MISSILES_NUMBER = {5, 15}
MISSILES_DELAY_MAX = 20
MISSILE_LAUNCH_PAD_ODDS = 5
