WINDOW_WIDTH = 400
WINDOW_HEIGHT = 620

OPTIONS = {
  fullscreen = false,
  vsync = true,
  resizable = false
}

PLAYER_WIDTH = 39
PLAYER_HEIGHT = 33
PLAYER_JUMP = 14
PLAYER_SLIDE = 4
PLAYER_FALLING_WIDTH = 39
PLAYER_FALLING_HEIGHT = 45

GRAVITY = 20
FRICTION = 10

PLATFORM_WIDTH = 39
PLATFORM_HEIGHT = 15
PLATFORM_GAP_X = 160
PLATFORM_GAP_Y = 120
