WINDOW_WIDTH = 540
WINDOW_HEIGHT = 380
WINDOW_PADDING = 10

PLAYING_WIDTH = WINDOW_WIDTH - WINDOW_PADDING * 2
PLAYING_HEIGHT = WINDOW_HEIGHT - WINDOW_PADDING * 2

COUNTDOWN_DELAY = 2.5
FEEDBACK_DELAY = 2.5
PROGRESS_BAR_DELAY = 5
PROGRESS_BAR_HEIGHT = 6

CAMERA_SHAKE = {
    ["label"] = "shake",
    ["interval"] = 0.1,
    ["x"] = 2,
    ["y"] = 2
}
