WINDOW_WIDTH = 540
WINDOW_HEIGHT = 380
WINDOW_PADDING = 10

PLAYING_WIDTH = WINDOW_WIDTH - WINDOW_PADDING * 2
PLAYING_HEIGHT = WINDOW_HEIGHT - WINDOW_PADDING * 2

COUNTDOWN_FEEBACK = 2
COUNTDOWN_LEVEL = 5
COUNTDOWN_LEVEL_BAR_HEIGHT = 6
