WINDOW_WIDTH = 672
WINDOW_HEIGHT = 484

OPTIONS = {
  fullscreen = false,
  vsync = true,
  resizable = false
}

PLAYER_SPEED = 200

BULLET_SPEED = 300
BULLET_WIDTH = 3
BULLET_HEIGHT = 15
BULLET_PARTICLES_WIDTH = 24
BULLET_PARTICLES_HEIGHT = 21

ROWS = 5
COLUMNS = 8
ALIEN_JUMP_X = 16
ALIEN_JUMP_Y = 32
ALIEN_WIDTH = 24
ALIEN_HEIGHT = 21
ALIEN_GAP_X = 16
ALIEN_GAP_Y = 12
