TITLE = "Pocketsies"

WINDOW_WIDTH = 520
WINDOW_HEIGHT = 340

TABLE_MARGIN = 10
TABLE_WIDTH = WINDOW_WIDTH - TABLE_MARGIN * 2
TABLE_HEIGHT = WINDOW_HEIGHT - TABLE_MARGIN * 2

TABLE_LINE_WIDTH = 6
TABLE_PADDING = 18
TABLE_INNER_WIDTH = TABLE_WIDTH - TABLE_PADDING * 2
TABLE_INNER_HEIGHT = TABLE_HEIGHT - TABLE_PADDING * 2

POCKET_RADIUS = 18
POCKET_INNER_RADIUS = POCKET_RADIUS - TABLE_LINE_WIDTH / 2
POCKET_PADDING = 26

BALL_SIZE = 12
CUE_LENGTH = 80
