TITLE = "Space Invaders"

WINDOW_WIDTH = 708
WINDOW_HEIGHT = 484
WINDOW_PADDING = 8

INVADERS = 3
VARIETIES = 2
INVADER_WIDTH = 24
INVADER_HEIGHT = 21

INVADER_BONUS_WIDTH = 39
INVADER_BONUS_HEIGHT = 18

PLAYER_WIDTH = 27
PLAYER_HEIGHT = 21
