TITLE = "Space Invaders"

PLAYING_AREA_WIDTH = 588
PLAYING_AREA_HEIGHT = 380
DATA_HEIGHT = 60

WINDOW_PADDING = 8
WINDOW_WIDTH = PLAYING_AREA_WIDTH + WINDOW_PADDING * 2
WINDOW_HEIGHT = PLAYING_AREA_HEIGHT + DATA_HEIGHT + WINDOW_PADDING * 2

INVADER_TYPES = 3
INVADER_POINTS_MULTIPLIER = 10
INVADER_FRAMES = 2
INVADER_WIDTH = 24
INVADER_HEIGHT = 21

INVADER_BONUS_WIDTH = 39
INVADER_BONUS_HEIGHT = 18

PLAYER_WIDTH = 27
PLAYER_HEIGHT = 21

PROJECTILE_WIDTH = 3
PROJECTILE_HEIGHT = 15

COLLISION_INVADER_WIDTH = 24
COLLISION_INVADER_HEIGHT = 21

COLLISION_PLAYER_WIDTH = 30
COLLISION_PLAYER_HEIGHT = 18
COLLISION_PLAYER_FRAMES = 2
