WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 512
VIRTUAL_HEIGHT = 288
BACKGROUND_SCROLL_SPEED = 18
BACKGROUND_SCROLL_THRESHOLD = 512

OPTIONS = {
  fullscreen = false,
  vsync = true,
  resizable = true
}

ROWS = 8
COLUMNS = 8
TILE_WIDTH = 32
TILE_HEIGHT = 32
