TITLE = "Excavation"

TEXTURE_SIZE = 8
COLUMNS = 22
ROWS = 14

VIRTUAL_WIDTH = TEXTURE_SIZE * COLUMNS
VIRTUAL_HEIGHT = TEXTURE_SIZE * ROWS

WINDOW_SCALE = 3
WINDOW_WIDTH = VIRTUAL_WIDTH * WINDOW_SCALE
WINDOW_HEIGHT = VIRTUAL_HEIGHT * WINDOW_SCALE

OPTIONS = {
  fullscreen = false,
  vsync = true,
  resizable = true
}

TEXTURE_SIZE = 8
TEXTURE_TYPES = 6

GEM_SIZES = {16, 24, 32}
GEM_COLORS = {"blue", "green", "red", "rose"}

TOOLS = {"pickaxe", "hammer"}
TOOLS_TYPE = {"outline", "fill"}
TOOLS_WIDTH = 21
TOOLS_HEIGHT = 22
