CELL_SIZE = 8

PADDING_COLUMNS = 1
BORDER_COLUMNS = 1
GRID_COLUMNS = 10
GRID_ROWS = 18
INFO_COLUMNS = 8

VIRTUAL_WIDTH = CELL_SIZE * (PADDING_COLUMNS * 2 + BORDER_COLUMNS * 2 + GRID_COLUMNS + INFO_COLUMNS)
VIRTUAL_HEIGHT = CELL_SIZE * GRID_ROWS

local SCALE = math.floor(700 / VIRTUAL_WIDTH)

WINDOW_WIDTH = VIRTUAL_WIDTH * SCALE
WINDOW_HEIGHT = VIRTUAL_HEIGHT * SCALE
