CELL_SIZE = 8

GRID_COLUMNS = 10
GRID_ROWS = 18

BORDER_COLUMNS = 1
PADDING_COLUMNS = 1
INFO_COLUMNS = 8

GRID_WIDTH = CELL_SIZE * (GRID_COLUMNS + BORDER_COLUMNS * 2)
GRID_HEIGHT = CELL_SIZE * GRID_ROWS

VIRTUAL_WIDTH = GRID_WIDTH + CELL_SIZE * (PADDING_COLUMNS * 2 + INFO_COLUMNS)
VIRTUAL_HEIGHT = GRID_HEIGHT

local SCALE = math.floor(700 / VIRTUAL_WIDTH)

WINDOW_WIDTH = VIRTUAL_WIDTH * SCALE
WINDOW_HEIGHT = VIRTUAL_HEIGHT * SCALE
