CELL_SIZE = 8

WHITESPACE_COLUMNS = 1 -- before the grid, between the grid and game data, after the game data
BORDER_COLUMNS = 1 -- around the grid
GRID_COLUMNS = 10
GRID_ROWS = 18
GAME_DATA_COLUMNS = 8

COLUMNS = WHITESPACE_COLUMNS * 3 + BORDER_COLUMNS * 2 + GRID_COLUMNS + GAME_DATA_COLUMNS
ROWS = GRID_ROWS

VIRTUAL_WIDTH = CELL_SIZE * COLUMNS
VIRTUAL_HEIGHT = CELL_SIZE * ROWS

local SCALE = math.floor(700 / VIRTUAL_WIDTH)

WINDOW_WIDTH = VIRTUAL_WIDTH * SCALE
WINDOW_HEIGHT = VIRTUAL_HEIGHT * SCALE
