MAZE_DIMENSION = 14
CELL_SIZE = 30
MAZE_SIZE = CELL_SIZE * MAZE_DIMENSION

WINDOW_PADDING = 10
WINDOW_MARGIN_TOP = 28

WINDOW_WIDTH = MAZE_SIZE + WINDOW_PADDING * 2
WINDOW_HEIGHT = MAZE_SIZE + WINDOW_MARGIN_TOP + WINDOW_PADDING * 2

UPDATE_INTERVAL = 0.5
UPDATE_TWEEN = 0.4

PROGRESS_MAX = 100
PROGRESS_INITIAL = 0
PROGRESS_STEPS = 5
