COLUMNS = 7
ROWS = 11

PADDING_X = 28
PADDING_Y = 24

CELL_SIZE = 50

MENU_HEIGHT = 52

WINDOW_WIDTH = COLUMNS * CELL_SIZE + PADDING_X * 2
WINDOW_HEIGHT = ROWS * CELL_SIZE + PADDING_Y * 2 + MENU_HEIGHT

MINES = 10
